version: '3.8'

services:
  jambonz-app:
    build: ./jambonz_app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      NODE_ENV: production
      LOGLEVEL: debug
      HTTP_PORT: 3000
      JAMBONZ_ACCOUNT_SID: 9351f46a-678c-43f5-b8a6-d4eb58d131af
      JAMBONZ_API_KEY: 1cf2f4f4-64c4-4249-9a3e-5bb4cb597c2a
      JAMBONZ_REST_API_BASE_URL: https://jambonz.us
      WEBHOOK_SECRET: wh_secret_cJqgtMDPzDhhnjmaJH6Mtk
      HTTP_PASSWORD: ''
      HTTP_USERNAME: ''
      REDIS_URL: redis://redis:6379

  mysql:
    image: mysql:8.0.32
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "brainai"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    expose:
      - "6379"

  brain-ai:
    build: ./brain_ai
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - mysql

volumes:
  redis_data:
  mysql-data:
